# Generated by Django 3.0.6 on 2020-05-08 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.IntegerField(primary_key=True, serialize=False)),
                ('task_title', models.CharField(max_length=25)),
                ('task_description', models.CharField(max_length=300)),
                ('start_date', models.DateTimeField(auto_now=True, verbose_name='Task Created')),
                ('deadline', models.DateTimeField(verbose_name='Task Deadline')),
                ('status', models.CharField(choices=[('started', 'Started'), ('ongoing', 'Ongoing'), ('postponed', 'Postponed'), ('completed', 'Completed')], default='started', max_length=25)),
            ],
        ),
    ]
