# Generated by Django 3.0.6 on 2020-05-10 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SimpleProject', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='groups',
            field=models.CharField(choices=[('Designers', 'Designers'), ('Programmers', 'Programmers'), ('Marketing', 'Marketing'), ('HR and Payroll', 'HR and Payroll'), ('Managers', 'Managers')], default='Managers', max_length=25),
        ),
    ]
